In [1]:
import pandas as pd
import numpy as np

In [2]:
laps = pd.read_csv('../data/raw/monza_2023_laps.csv')
print(laps.shape)
laps.head()

(958, 31)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:23:49.780000,VER,1,0 days 00:01:27.905000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:29.666000,...,True,Red Bull Racing,0 days 01:22:21.726000,2023-09-03 13:23:22.771,1,2.0,False,NaN,False,False
1,0 days 01:25:15.943000,VER,1,0 days 00:01:26.163000,2.0,1.0,NaN,NaN,0 days 00:00:28.274000,0 days 00:00:29.543000,...,True,Red Bull Racing,0 days 01:23:49.780000,2023-09-03 13:24:50.825,1,2.0,False,NaN,False,True
2,0 days 01:26:41.645000,VER,1,0 days 00:01:25.702000,3.0,1.0,NaN,NaN,0 days 00:00:28.097000,0 days 00:00:29.320000,...,True,Red Bull Racing,0 days 01:25:15.943000,2023-09-03 13:26:16.988,1,2.0,False,NaN,False,True
3,0 days 01:28:07.695000,VER,1,0 days 00:01:26.050000,4.0,1.0,NaN,NaN,0 days 00:00:28.145000,0 days 00:00:29.474000,...,True,Red Bull Racing,0 days 01:26:41.645000,2023-09-03 13:27:42.690,1,2.0,False,NaN,False,True
4,0 days 01:29:33.871000,VER,1,0 days 00:01:26.176000,5.0,1.0,NaN,NaN,0 days 00:00:28.155000,0 days 00:00:29.514000,...,True,Red Bull Racing,0 days 01:28:07.695000,2023-09-03 13:29:08.740,1,2.0,False,NaN,False,True

In [4]:
laps = laps[laps['IsAccurate'] == True]
print(laps.shape)

(878, 31)

In [5]:
laps = laps[laps['Deleted'] == False]
print(laps.shape)

(864, 31)

In [6]:
laps = laps.dropna(subset=['LapTime', 'Position', 'Sector1Time', 'Sector2Time', 'Sector3Time'])
print(laps.shape)

(864, 31)

In [7]:
time_cols = ['LapTime', 'Sector1Time', 'Sector2Time', 'Sector3Time']

for col in time_cols:
    laps[col] = pd.to_timedelta(laps[col]).dt.total_seconds()

laps[time_cols].head()

   LapTime  Sector1Time  Sector2Time  Sector3Time
1   86.163       28.274       29.543       28.346
2   85.702       28.097       29.320       28.285
3   86.050       28.145       29.474       28.431
4   86.176       28.155       29.514       28.507
5   86.837       28.700       29.662       28.475

In [8]:
key_cols = ['Driver', 'LapTime', 'Position', 'Compound', 'TyreLife', 'Team']
print(laps[key_cols].isnull().sum())

Driver      0
LapTime     0
Position    0
Compound    0
TyreLife    0
Team        0
dtype: int64

In [16]:
laps.to_csv('../data/processed/monza_2023_laps_clean.csv', index=False)
print("Saved successfully")
print(f"Final shape: {laps.shape}")

Saved successfully
Final shape: (864, 31)